baseURL = 'https://www.velengel.com/blog'
languageCode = 'ja'
title = 'Vel Labs(ベル研究所)'
theme = 'ananke'
publishDir = 'docs'

[taxonomies]
  tag = "tags"

[params]
  custom_css = ["custom.css"]
  show_reading_time = true
  [[params.ananke_socials]]
  name = "github"
  url = "https://github.com/velengel"
