baseURL = 'https://www.velengel.com/blog'
languageCode = 'ja'
title = 'Vel Labs(ベル研究所)'
theme = 'nagoya'
publishDir = 'docs'

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"
  search = "search"

[params]
  author = "velengel"
  authorLink = "https://github.com/velengel"
  description = "エンジニアリングマネージャー見習いの個人開発備忘録"
  showAuthor = true
