baseURL = 'https://www.velengel.com/blog'
languageCode = 'ja'
title = 'Vel Labs(ベル研究所)'
theme = 'nagoya'
publishDir = 'docs'

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"
  search = "search"
